# Generated by Django 6.0.2 on 2026-02-18 13:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builderitem',
            options={'ordering': ['group', 'name'], 'verbose_name': 'آیتم سازنده پک', 'verbose_name_plural': 'آیتم های سازنده پک'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-featured', 'name'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='group',
            field=models.CharField(choices=[('packaging', 'بسته بندی'), ('fruit', 'میوه'), ('drink', 'نوشیدنی'), ('snack', 'اسنک'), ('addon', 'افزودنی')], help_text='نکته: گروه آیتم را انتخاب کنید.', max_length=20, verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='image',
            field=models.ImageField(blank=True, help_text='نکته: بارگذاری تصویر برای نمایش بهتر این آیتم.', null=True, upload_to='builder-items/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='name',
            field=models.CharField(help_text='نکته: نام آیتم سازنده پک را وارد کنید.', max_length=255, verbose_name='نام آیتم'),
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='price',
            field=models.PositiveIntegerField(help_text='نکته: قیمت این آیتم را به تومان وارد کنید.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='builderitem',
            name='required',
            field=models.BooleanField(default=True, help_text='نکته: اگر فعال باشد انتخاب این آیتم برای ساخت پک الزامی است.', verbose_name='اجباری'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='نکته: می توانید ایموجی یا آیکون کوتاه وارد کنید.', max_length=32, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='نکته: نام نمایشی دسته بندی را وارد کنید.', max_length=128, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='نکته: نسخه انگلیسی و یکتا برای آدرس دهی (مثال: economic).', max_length=128, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='نکته: اگر غیرفعال باشد، سفارش این محصول ممکن نیست.', verbose_name='موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='نکته: دسته بندی های مرتبط با این محصول را انتخاب کنید.', related_name='products', to='catalog.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contents',
            field=models.JSONField(blank=True, default=list, help_text='نکته: اقلام محصول را به صورت لیست JSON وارد کنید.', verbose_name='اقلام داخل پک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='نکته: این زمان به صورت خودکار ثبت می شود.', verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='نکته: توضیحات کوتاه و شفاف درباره محصول بنویسید.', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='event_types',
            field=models.JSONField(blank=True, default=list, help_text='نکته: لیست نوع مراسم به صورت JSON (مثال: ["conference"]).', verbose_name='نوع مراسم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='نکته: اگر فعال باشد، محصول در بخش ویژه نمایش داده می شود.', verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='نکته: تصویر با کیفیت و نسبت مناسب بارگذاری کنید.', null=True, upload_to='products/', verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='نکته: نام کامل محصول برای نمایش در سایت.', max_length=255, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='نکته: مبلغ را به تومان وارد کنید. برای محصولات توافقی خالی بگذارید.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='نکته: این زمان بعد از هر ویرایش به صورت خودکار بروزرسانی می شود.', verbose_name='آخرین بروزرسانی'),
        ),
    ]
