# Generated by Django 6.0.2 on 2026-02-22 20:16

from django.db import migrations, models
from django.utils.text import slugify


def _populate_product_url_slugs(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")

    existing_slugs = set(
        Product.objects.exclude(url_slug__isnull=True)
        .exclude(url_slug__exact="")
        .values_list("url_slug", flat=True)
    )

    for product in Product.objects.all().order_by("created_at", "id"):
        base_slug = slugify((product.url_slug or "").strip()) if product.url_slug else ""
        if not base_slug:
            base_slug = slugify(product.name or "")
        if not base_slug:
            base_slug = f"product-{str(product.id)[:8]}"

        candidate = base_slug
        suffix = 2
        while candidate in existing_slugs:
            candidate = f"{base_slug}-{suffix}"
            suffix += 1

        product.url_slug = candidate
        product.save(update_fields=["url_slug"])
        existing_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_sync_event_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url_slug",
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="نکته: آدرس محصول را به انگلیسی و یکتا وارد کنید (مثال: vip-pack).",
                max_length=180,
                verbose_name="آدرس محصول (URI)",
            ),
        ),
        migrations.RunPython(
            code=_populate_product_url_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="product",
            name="url_slug",
            field=models.SlugField(
                blank=True,
                help_text="نکته: آدرس محصول را به انگلیسی و یکتا وارد کنید (مثال: vip-pack).",
                max_length=180,
                unique=True,
                verbose_name="آدرس محصول (URI)",
            ),
        ),
    ]
