# Generated by Django 6.0.2 on 2026-02-22 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_url_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه')),
                ('name', models.CharField(help_text='نکته: نام نمایشی تگ محصول را وارد کنید.', max_length=128, verbose_name='نام تگ')),
                ('slug', models.SlugField(help_text='نکته: نسخه انگلیسی و یکتا برای آدرس دهی (مثال: fast-delivery).', max_length=128, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='نکته: تگ های مرتبط با این محصول را انتخاب کنید.', related_name='products', to='catalog.tag', verbose_name='تگ ها'),
        ),
    ]
