# Generated by Django 6.0.2 on 2026-02-18 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='allowed_provinces',
            field=models.JSONField(blank=True, default=list, help_text='نکته: استان های قابل ارسال را به صورت لیست JSON وارد کنید.', verbose_name='استان های مجاز'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='delivery_windows',
            field=models.JSONField(blank=True, default=list, help_text='نکته: بازه های زمانی تحویل را به صورت لیست JSON وارد کنید.', verbose_name='بازه های تحویل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, help_text='نکته: تنظیمات سایت فقط یک رکورد دارد و شناسه آن همواره 1 است.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='lead_time_hours',
            field=models.PositiveIntegerField(default=48, help_text='نکته: فاصله زمانی لازم از ثبت سفارش تا زمان تحویل.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل زمان آماده سازی (ساعت)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='min_order_qty',
            field=models.PositiveIntegerField(default=40, help_text='نکته: مشتری باید حداقل این تعداد را برای ثبت سفارش وارد کند.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='حداقل تعداد سفارش'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='نکته: روش های پرداخت فعال/غیرفعال را به صورت JSON تنظیم کنید.', verbose_name='روش های پرداخت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='نکته: زمان آخرین بروزرسانی این تنظیمات.', verbose_name='آخرین بروزرسانی'),
        ),
    ]
