# Generated by Django 6.0.2 on 2026-02-18 13:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_builderitem_options_alter_category_options_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم های سفارش'},
        ),
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['created_at'], 'verbose_name': 'یادداشت سفارش', 'verbose_name_plural': 'یادداشت های سفارش'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='نکته: زمان ثبت سفارش به صورت خودکار.', verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.TextField(help_text='نکته: آدرس کامل و دقیق برای ارسال سفارش.', verbose_name='آدرس تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(help_text='نکته: نام و نام خانوادگی گیرنده سفارش.', max_length=255, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='نکته: توضیحات تکمیلی مشتری (اختیاری).', verbose_name='یادداشت مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(help_text='نکته: شماره تماس معتبر مشتری (فرمت 09xxxxxxxxx).', max_length=32, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_province',
            field=models.CharField(help_text='نکته: استان مقصد برای تحویل سفارش.', max_length=128, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(help_text='نکته: تاریخ تحویل سفارش.', verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_window',
            field=models.CharField(help_text='نکته: بازه زمانی انتخابی برای تحویل.', max_length=64, verbose_name='بازه زمانی تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(help_text='نکته: روش پرداخت انتخاب شده توسط مشتری.', max_length=64, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(db_index=True, help_text='نکته: کد یکتای سفارش به صورت خودکار تولید می شود.', max_length=20, unique=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('preparing', 'در حال آماده سازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده')], default='pending', help_text='نکته: وضعیت جاری سفارش را مشخص می کند.', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, help_text='نکته: مجموع نهایی سفارش به تومان.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='نکته: زمان آخرین ویرایش سفارش به صورت خودکار.', verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='custom_config',
            field=models.JSONField(blank=True, default=dict, help_text='نکته: جزییات ترکیب پک سفارشی به صورت JSON.', null=True, verbose_name='پیکربندی سفارشی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_custom_pack',
            field=models.BooleanField(default=False, help_text='نکته: اگر فعال باشد آیتم از نوع پک سفارشی است.', verbose_name='پک سفارشی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(help_text='نکته: نام نمایشی آیتم سفارش.', max_length=255, verbose_name='نام آیتم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='نکته: سفارشی که این آیتم به آن تعلق دارد.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(help_text='نکته: قیمت هر واحد آیتم به تومان.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='نکته: در صورت انتخاب محصول آماده، این فیلد پر می شود.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='محصول مرجع'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='نکته: تعداد این آیتم در سفارش.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='نکته: زمان ثبت این یادداشت به صورت خودکار.', verbose_name='زمان ثبت یادداشت'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='نکته: کاربری که این یادداشت را ثبت کرده است.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notes', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='نکته: این شناسه به صورت خودکار ساخته می شود.', primary_key=True, serialize=False, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='note',
            field=models.TextField(help_text='نکته: توضیحات داخلی مربوط به سفارش را ثبت کنید.', verbose_name='متن یادداشت'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(help_text='نکته: سفارشی که این یادداشت برای آن ثبت شده است.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.order', verbose_name='سفارش'),
        ),
    ]
